services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./test_folders:/test_folders
      - ./test_folders/qbitorrent/anime:/test_folders/qbitorrent/anime
      - ./test_folders/plex/anime:/test_folders/plex/anime
      - ./test_folders/qbitorrent/movie:/test_folders/qbitorrent/movie
      - ./test_folders/plex/movies:/test_folders/plex/movies
      - ./test_folders/qbitorrent/animated_movie:/test_folders/qbitorrent/animated_movie
      - ./test_folders/plex/animated_movies:/test_folders/plex/animated_movies
    env_file:
      - dev.env
    healthcheck:
      test: curl --fail http://localhost:1234/healthcheck || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
