services:
  manager:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${HOST_ROOT_DRIVE}:${CONTAINER_ROOT_DRIVE}
    env_file:
      - .env
    restart: always
    healthcheck:
      test: curl --fail http://localhost:1234/healthcheck || exit 1
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 5s
